/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuiltForYouRouteImport } from './routes/built-for-you'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvailableSitesRouteImport } from './routes/admin.available-sites'
import { Route as AdminBackgroundsRouteImport } from './routes/admin.backgrounds'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin.blog-categories'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminFooterRouteImport } from './routes/admin.footer'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminScreenshotsRouteImport } from './routes/admin.screenshots'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSitePagesRouteImport } from './routes/admin.site-pages'
import { Route as AdminSportsRouteImport } from './routes/admin.sports'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as SportsSlugRouteImport } from './routes/sports.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiltForYouRoute = BuiltForYouRouteImport.update({
  id: '/built-for-you',
  path: '/built-for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailableSitesRoute = AdminAvailableSitesRouteImport.update({
  id: '/available-sites',
  path: '/available-sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackgroundsRoute = AdminBackgroundsRouteImport.update({
  id: '/backgrounds',
  path: '/backgrounds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/blog-categories',
  path: '/blog-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScreenshotsRoute = AdminScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitePagesRoute = AdminSitePagesRouteImport.update({
  id: '/site-pages',
  path: '/site-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GamesRoute,
} as any)
const SportsSlugRoute = SportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/built-for-you': typeof BuiltForYouRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/sports': typeof SportsRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/available-sites': typeof AdminAvailableSitesRoute
  '/admin/backgrounds': typeof AdminBackgroundsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/screenshots': typeof AdminScreenshotsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-pages': typeof AdminSitePagesRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/sports/$slug': typeof SportsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/built-for-you': typeof BuiltForYouRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/sports': typeof SportsRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/available-sites': typeof AdminAvailableSitesRoute
  '/admin/backgrounds': typeof AdminBackgroundsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/screenshots': typeof AdminScreenshotsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-pages': typeof AdminSitePagesRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/sports/$slug': typeof SportsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/built-for-you': typeof BuiltForYouRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/sports': typeof SportsRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/available-sites': typeof AdminAvailableSitesRoute
  '/admin/backgrounds': typeof AdminBackgroundsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/screenshots': typeof AdminScreenshotsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-pages': typeof AdminSitePagesRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin_/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/sports/$slug': typeof SportsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/built-for-you'
    | '/casino'
    | '/contact'
    | '/faq'
    | '/games'
    | '/how-it-works'
    | '/privacy-policy'
    | '/responsible-gaming'
    | '/sports'
    | '/terms'
    | '/admin/available-sites'
    | '/admin/backgrounds'
    | '/admin/blog'
    | '/admin/blog-categories'
    | '/admin/faq'
    | '/admin/footer'
    | '/admin/games'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/promotions'
    | '/admin/screenshots'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site-pages'
    | '/admin/sports'
    | '/admin/support'
    | '/admin/theme'
    | '/admin/login'
    | '/blog/$slug'
    | '/games/$slug'
    | '/sports/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/built-for-you'
    | '/casino'
    | '/contact'
    | '/faq'
    | '/games'
    | '/how-it-works'
    | '/privacy-policy'
    | '/responsible-gaming'
    | '/sports'
    | '/terms'
    | '/admin/available-sites'
    | '/admin/backgrounds'
    | '/admin/blog'
    | '/admin/blog-categories'
    | '/admin/faq'
    | '/admin/footer'
    | '/admin/games'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/promotions'
    | '/admin/screenshots'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site-pages'
    | '/admin/sports'
    | '/admin/support'
    | '/admin/theme'
    | '/admin/login'
    | '/blog/$slug'
    | '/games/$slug'
    | '/sports/$slug'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/built-for-you'
    | '/casino'
    | '/contact'
    | '/faq'
    | '/games'
    | '/how-it-works'
    | '/privacy-policy'
    | '/responsible-gaming'
    | '/sports'
    | '/terms'
    | '/admin/available-sites'
    | '/admin/backgrounds'
    | '/admin/blog'
    | '/admin/blog-categories'
    | '/admin/faq'
    | '/admin/footer'
    | '/admin/games'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/promotions'
    | '/admin/screenshots'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site-pages'
    | '/admin/sports'
    | '/admin/support'
    | '/admin/theme'
    | '/admin_/login'
    | '/blog/$slug'
    | '/games/$slug'
    | '/sports/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuiltForYouRoute: typeof BuiltForYouRoute
  CasinoRoute: typeof CasinoRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  SportsRoute: typeof SportsRouteWithChildren
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built-for-you': {
      id: '/built-for-you'
      path: '/built-for-you'
      fullPath: '/built-for-you'
      preLoaderRoute: typeof BuiltForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/available-sites': {
      id: '/admin/available-sites'
      path: '/available-sites'
      fullPath: '/admin/available-sites'
      preLoaderRoute: typeof AdminAvailableSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backgrounds': {
      id: '/admin/backgrounds'
      path: '/backgrounds'
      fullPath: '/admin/backgrounds'
      preLoaderRoute: typeof AdminBackgroundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-categories': {
      id: '/admin/blog-categories'
      path: '/blog-categories'
      fullPath: '/admin/blog-categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/screenshots': {
      id: '/admin/screenshots'
      path: '/screenshots'
      fullPath: '/admin/screenshots'
      preLoaderRoute: typeof AdminScreenshotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-pages': {
      id: '/admin/site-pages'
      path: '/site-pages'
      fullPath: '/admin/site-pages'
      preLoaderRoute: typeof AdminSitePagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof GamesRoute
    }
    '/sports/$slug': {
      id: '/sports/$slug'
      path: '/$slug'
      fullPath: '/sports/$slug'
      preLoaderRoute: typeof SportsSlugRouteImport
      parentRoute: typeof SportsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAvailableSitesRoute: typeof AdminAvailableSitesRoute
  AdminBackgroundsRoute: typeof AdminBackgroundsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminScreenshotsRoute: typeof AdminScreenshotsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSitePagesRoute: typeof AdminSitePagesRoute
  AdminSportsRoute: typeof AdminSportsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvailableSitesRoute: AdminAvailableSitesRoute,
  AdminBackgroundsRoute: AdminBackgroundsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminScreenshotsRoute: AdminScreenshotsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSitePagesRoute: AdminSitePagesRoute,
  AdminSportsRoute: AdminSportsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GamesRouteChildren {
  GamesSlugRoute: typeof GamesSlugRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesSlugRoute: GamesSlugRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface SportsRouteChildren {
  SportsSlugRoute: typeof SportsSlugRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSlugRoute: SportsSlugRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BuiltForYouRoute: BuiltForYouRoute,
  CasinoRoute: CasinoRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  SportsRoute: SportsRouteWithChildren,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
